### ISSUE TITLE
The getter 'INFINITY' isn't defined for the class 'double'

### ISSUE THREAD

**Issue by danieldcoded** [durannumit/flutter_onboarding_screen#2]
As read in the title I am getting an error. When trying to compile the project I get this:

```
Compiler message:
lib/UI/pages.dart:37:23: Error: Getter not found: 'INFINITY'.
        width: double.INFINITY,
                      ^^^^^^^^
Compiler failed on /Users/user/Desktop/flutter_onboarding_screen-master/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1
```

Any idea why this is happening?

**Comment by Condelab** [comment]
look [here](https://github.com/google/charts/issues/86)

The latest dev builds of Dart 2 has started to remove the old capital letter constants.

so just use `double.infinity` and all should be fine.

**Comment by danieldcoded** [comment]
That worked. Thank you 👍
