### ISSUE TITLE
Request to Add Licence

### ISSUE THREAD

**Issue by maheshwari-1153** [durannumit/flutter_onboarding_screen#4]
I am Maheshwari from team [GeekyAnts](https://geekyants.com/). On behalf of [Start Flutter](https://startflutter.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.
Let me know if you are interested showcase your product in our open source website. If yes, then I request you to add MIT Licence in your repo.
Looking forward to hear from you.

**Comment by durannumit** [comment]
Of course , I want to share with community. I'm adding MIT licence. Thank you @maheshwari-1153

**Comment by maheshwari-1153** [comment]
Hello,

Thanks for your reply. I will check & let you know.

Best Regards,
Maheshwari Shukla

**Comment by maheshwari-1153** [comment]
Hello,

I have added your product in our Start-Flutter-Website
<https://startflutter.com/themes/flutter-onboarding-screen/>. Please have a
look at it.

Feel free to reach out regarding any other queries.

Best Regards,
Maheshwari Shukla
